### ISSUE TITLE
CertStorageError: live directory exists for staging.<redacted>.net

### ISSUE THREAD

**Issue by boldandbusted** [inviqa/chef-certbot#13]
Howdy. I'm using Certbot with version 0.1.2 of this cookbook. I get this error on *first-run* of certbot. I checked that the rpm packages are not inadvertantly creating /etc/letsencrypt/live; they are not. I grepped the logs, and only the errant line below mentions this directory. Also, I checked cron, and cron renew scripts had been added, but had not yet run.

```shell
[root@ip-10-0-0-76 letsencrypt]# rpm -qa | grep certbot
certbot-0.9.3-1.el7.noarch
python2-certbot-0.9.3-1.el7.noarch
[root@ip-10-0-0-76 letsencrypt]# cat /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core) 
[root@ip-10-0-0-76 letsencrypt]# 
```

Please let me know if I can provide more information and context. Thanks! :)

Log follows: 
```shell
2017-02-01 02:04:43,969:DEBUG:acme.client:Received response <Response [200]> (headers: {'content-length': '1199', 'strict-transport-security': 'max-age=604800', 'boulder-request-id': 'fuVA4FzY9VEAmaWgQ_kEyCfqbw63ZljRcANOGi9waFk', 'expires': 'Wed, 01 Feb 2017 02:04:43 GMT', 'server': 'nginx', 'connection': 'keep-alive', 'pragma': 'no-cache', 'cache-control': 'max-age=0, no-cache, no-store', 'date': 'Wed, 01 Feb 2017 02:04:43 GMT', 'x-frame-options': 'DENY', 'content-type': 'application/pkix-cert', 'replay-nonce': 'WHuoGapXl5gWuoFVoOANqilrD0tS1q49A4YudcITais'}): '0\x82\x04\xab0\x82\x02\x93\xa0\x03\x02\x01\x02\x02\x11\x00\x8b\xe1*\x0eYD\xed<Td1\xf0\x97aO\xe50\r\x06\t*\x86H\x86\xf7\r\x01\x01\x0b\x05\x000\x1a1\x180\x16\x06\x03U\x04\x03\x0c\x0fFake LE Root X10\x1e\x17\r160523220759Z\x17\r360523220759Z0"1 0\x1e\x06\x03U\x04\x03\x0c\x17Fake LE Intermediate X10\x82\x01"0\r\x06\t*\x86H\x86\xf7\r\x01\x01\x01\x05\x00\x03\x82\x01\x0f\x000\x82\x01\n\x02\x82\x01\x01\x00\xedX\xac\x92\x0e~\xebY\x979\x82\x08\xf3\xdd\x90t\xf23\xb8\xc6\xd8\xb7\xbb2\r|>lC\xb2\xe3\xee\x1c\xde\xb5D\xfe\xc1\n\x1b\xfa%\xd2fHg\xbf\x1f\x88\xbd\xd6\xd7\x17\x9f\xf2\xb7\xc6\x96>\x95\n\x9c\xfc\xa6\xa0\xbclb"9\x81\x00K\xc4\xd0\xf3!\xe748\x86\x9f\x95j\x80\xafof\xec\x9f>4\xdb@\xa4C|\x9d\x91g\x7fv\xe1z\x16V\xec\x0cfKY\xb4ft\xact|4\x17\x0f\x9b\x82,O\x83c\x10\xf6Ohy\xf1^\xa9\xaf\xbb*\xa7e\xcf\x96\xdb\xadF\x15\xda\xfa%\xc6\x10\xc5\xb6r82\x1f\x01\x89`\x8d\xc41\xf5\x1e,\xea\xf8b\x82p{"\x9c6V\xba\xb0\xaau\xea\xffi\xf2A\x9d\x0b>H\x14\x8b\xe8\xc5@\xa4{~w~s\x8c\x10\xfd\xd9\xf3\xb6%\xeezv\x13\x1f\xcc(\x0e)w\x89\xdf\x8d\x16\x85m\xd3\x8c=s\xa8\xb6Wy\xa0\xb2P\xd4g|\xe9\x96e_\'\x12\x1bG8V\xd4\tN\xeb\xfc\xa9#1\x93\xbd\x02\x03\x01\x00\x01\xa3\x81\xe30\x81\xe00\x0e\x06\x03U\x1d\x0f\x01\x01\xff\x04\x04\x03\x02\x01\x860\x12\x06\x03U\x1d\x13\x01\x01\xff\x04\x080\x06\x01\x01\xff\x02\x01\x000\x1d\x06\x03U\x1d\x0e\x04\x16\x04\x14\xc0\xcc\x03F\xb9X \xcc\\rp\xf3\xe1.\xcb \xa6\xf5h:0z\x06\x08+\x06\x01\x05\x05\x07\x01\x01\x04n0l04\x06\x08+\x06\x01\x05\x05\x070\x01\x86(http://ocsp.stg-root-x1.letsencrypt.org/04\x06\x08+\x06\x01\x05\x05\x070\x02\x86(http://cert.stg-root-x1.letsencrypt.org/0\x1f\x06\x03U\x1d#\x04\x180\x16\x80\x14\xc1&t\xa4\x8aD\xa0\xe6\xfa (\xd8\\#\x9aE\x88\x18y\xe00\r\x06\t*\x86H\x86\xf7\r\x01\x01\x0b\x05\x00\x03\x82\x02\x01\x00\x05\x84\xae\xe0\x89~|\x8d\x0caN699\x84\x8f\xedG\xa9\x0eC\xbf \x1e\xc8 :\xb0k\x99w\x08\xc5Pg\x95:\xfd\xcd\x9c\xbc\x9f\xa1\xfb\x94:1\x1bc\x98\xab\x14 \xed\x9e\xff\xb4rK\xa4Q\x93}\x97>\x10\xd9\x88\xd6\x19JV\xe14\xee\xde\'\x93\xb1\xa0\xbd\x00[\xc2J\x03G\'%\x92V\xd5\xaf\x07\x95\xc3\xc6\xca\x9a\xc2]J\xcc|\xf3\xc2\xbdw\xd9\xb1v\xae\xd1\xadk4\xaaV\xa2\xbd\x13N\xec\x18s\x02\x7f\xec\xe9\r\x05CUQ\xad\xa9\x93\xc7\xc1}\xca\xa9K^|N\xb6\xd5\xbf\x11#\xa5B\x97\x8a\x03\xdfC\xa5\x7f\xcac\xbb1\xb8$\xa0EDW%\xcc\xb4c\xa3\xf8{"I\x1f\x8d\x9f0\r\xae\xdfh\xe8\xd5_\x1e\xa7\xf9\xe5\x10\xdb\xd7\x080,\xeb\xf3\xfa\xcdXt\xbd\xa5\x81\x86@\xa2bclfT/a\xd7a\xfd\xf5|\x9f\xcda=\xbd\xbes(\xfd\xccTn\xa7y}aI\xda;<@\x1b\xf5\xfa\x91\x84y*V\xca\x94\xbc\x99HFk\xd7\xbdR\x93\xc0\xd0\x8f\xdd\xe0\xa3D \x88=0/\x8d_\xb8\x9e.\xfc\xea%\xf0\xc0V\r\xcf\xc9w>c\xcb\x0b$\x17Xj!\x9c\x9f"\x06o\xb9\x9eN\xce\xdb)\xda=U\xb4Se\xbe\xa6\xdd\xb0I[\xaft39\xcck\xf6\x7f\xd9m5e"a\x91\xc9\xd6i\x8e\xf7\xb8\xd2c\xfe\x98}\xd3\x94\x1f\xae\xa2F\xd4-\x0eA\xc1E\xd9\r\x06\xc3\x1b\x0f\xe1&\xd98\x01\x95\xdbG5"A|\x1d\xe9\x9b\xd1[\x96\x03\x9c\'ARY\xc5\x03X\x9e\xef;O\x8dMy`\xad\x1a\x1fE>\xa9W,3\xc5Z:t\xd0\xf4[6%Mg\x94V\xc3\xb8\xd3\x12j\x86\x05\x10DD}`\xb3\x8b\xc4\x9d\x0e\xe8/"\xd3\x11q\x00\xc2\x8e\xb5\'ht\xc0wD\x8c-\xed\x11P\xd2\xec\xad\x9f\x96y2\xa9\x18\x86S\x08\xdc\x9dm=\x14\xe9\xd6q-\xf5\xfc\x86\xb2\x90N;N`\x8b^<A\xab)\xfbs~\xb2\xfa\x8a\xa2j\x10\x82Sh\x03\x15'
2017-02-01 02:04:43,984:DEBUG:certbot.storage:Creating directory /etc/letsencrypt/archive.
2017-02-01 02:04:43,985:DEBUG:certbot.main:Exiting abnormally:
Traceback (most recent call last):
  File "/bin/certbot", line 9, in <module>
    load_entry_point('certbot==0.9.3', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 776, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 563, in obtain_cert
    action, _ = _auth_from_domains(le_client, config, domains, lineage)
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 100, in _auth_from_domains
    lineage = le_client.obtain_and_enroll_certificate(domains)
  File "/usr/lib/python2.7/site-packages/certbot/client.py", line 298, in obtain_and_enroll_certificate
    configuration.RenewerConfiguration(self.config.namespace))
  File "/usr/lib/python2.7/site-packages/certbot/storage.py", line 784, in new_lineage
    "live directory exists for " + lineagename)
CertStorageError: live directory exists for staging.<redacted>.net

**Comment by boldandbusted** [comment]
Ah, sorry for the noise! I found the issue was within my chef recipe. Thanks for the Certbot Cookbook! :)
